export default {
        'FU':['https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Shogi_fuhyo%28svg%29.svg/202px-Shogi_fuhyo%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Shogi_fuhyo%28svg%29.svg/202px-Shogi_fuhyo%28svg%29.svg.png'],
        'KY':['https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Shogi_kyosha%28svg%29.svg/202px-Shogi_kyosha%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Shogi_kyosha%28svg%29.svg/202px-Shogi_kyosha%28svg%29.svg.png'],
        'KE':['https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Shogi_keima.svg/202px-Shogi_keima.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Shogi_keima.svg/202px-Shogi_keima.svg.png'],
        'OU':['https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Shogi_gyokusho%28svg%29.svg/202px-Shogi_gyokusho%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Shogi_osho%28svg%29.svg/202px-Shogi_osho%28svg%29.svg.png'],
        'KA':['https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Shogi_kakugyo%28svg%29.svg/202px-Shogi_kakugyo%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Shogi_kakugyo%28svg%29.svg/202px-Shogi_kakugyo%28svg%29.svg.png'],
        'HI':['https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Shogi_hisha%28svg%29.svg/202px-Shogi_hisha%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Shogi_hisha%28svg%29.svg/202px-Shogi_hisha%28svg%29.svg.png'],
        'GI':['https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Shogi_ginsho%28svg%29.svg/202px-Shogi_ginsho%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Shogi_ginsho%28svg%29.svg/202px-Shogi_ginsho%28svg%29.svg.png'],
        'KI':['https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Shogi_kinsho%28svg%29.svg/202px-Shogi_kinsho%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Shogi_kinsho%28svg%29.svg/202px-Shogi_kinsho%28svg%29.svg.png'],
        'RY':['https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Shogi_ryuo%28svg%29.svg/202px-Shogi_ryuo%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Shogi_ryuo%28svg%29.svg/202px-Shogi_ryuo%28svg%29.svg.png'],
        'UM':['https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Shogi_ryuma%28svg%29.svg/202px-Shogi_ryuma%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Shogi_ryuma%28svg%29.svg/202px-Shogi_ryuma%28svg%29.svg.png'],
        'NG':['https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Shogi_narigin%28svg%29.svg/202px-Shogi_narigin%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Shogi_narigin%28svg%29.svg/202px-Shogi_narigin%28svg%29.svg.png'],
        'NK':['https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Shogi_narikei%28svg%29.svg/202px-Shogi_narikei%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Shogi_narikei%28svg%29.svg/202px-Shogi_narikei%28svg%29.svg.png'],
        'NY':['https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Shogi_narikyo%28svg%29.svg/202px-Shogi_narikyo%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Shogi_narikyo%28svg%29.svg/202px-Shogi_narikyo%28svg%29.svg.png'],
        'TO':['https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Shogi_tokin%28svg%29.svg/202px-Shogi_tokin%28svg%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Shogi_tokin%28svg%29.svg/202px-Shogi_tokin%28svg%29.svg.png']
}